/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function splitByCase(
  input: string,
  splitters?: Array<string> | undefined | null,
): Array<string>;
export function upperFirst(input: string): string;
export function lowerFirst(input: string): string;
export function pascalCase(input: string): string;
export function camelCase(input: string): string;
export function kebabCase(
  input: string,
  joiner?: string | undefined | null,
): string;
export function snakeCase(input: string): string;
